'use client';

import React, { useState } from 'react';
import { useApp } from '@/context/AppContext';
import { ReminderRule } from '@/types';
import { Card } from '@/components/common/Card';
import { Button } from '@/components/common/Button';
import { Badge } from '@/components/common/Badge';
import { Modal } from '@/components/common/Modal';
import { Input, Select } from '@/components/common/Input';
import { EmptyState } from '@/components/common/EmptyState';
import {
  BellRing,
  MessageSquare,
  Mail,
  Smartphone,
  CheckCircle2,
  AlertTriangle,
  Clock,
  Sparkles,
  CheckCheck,
} from 'lucide-react';

export function LembretesModule() {
  const { reminders, toggleReminder, updateReminderTemplate, showToast } = useApp();

  const [selectedRuleId, setSelectedRuleId] = useState<string>(reminders[0]?.id || '');
  const selectedRule = reminders.find((r) => r.id === selectedRuleId) || reminders[0];

  const [templateText, setTemplateText] = useState(selectedRule?.template || '');
  const [channel, setChannel] = useState<'whatsapp' | 'sms' | 'email'>(selectedRule?.channel || 'whatsapp');

  // Check valid variables from spec: {nome}, {data}, {hora}, {profissional}
  const validVariables = ['{nome}', '{data}', '{hora}', '{profissional}'];

  // Check for invalid variables like {nomee} as specified in spec:
  // "Este modelo usa uma variável que não existe: {nomee}. Corrija antes de ativar."
  const variableMatches = templateText.match(/\{[a-zA-Z0-9_]+\}/g) || [];
  const invalidVars = variableMatches.filter((v) => !validVariables.includes(v));

  // Preview generated by substituting mock values
  const previewText = templateText
    .replace('{nome}', 'Ana Souza')
    .replace('{data}', '01/10/2026')
    .replace('{hora}', '09:00')
    .replace('{profissional}', 'Dra. Marina Silveira');

  const handleSave = () => {
    if (invalidVars.length > 0) {
      showToast(`Este modelo usa uma variável que não existe: ${invalidVars[0]}. Corrija antes de ativar.`, 'warning');
      return;
    }
    updateReminderTemplate(selectedRule.id, templateText);
  };

  const insertVariable = (variable: string) => {
    setTemplateText((prev) => prev + ` ${variable} `);
  };

  return (
    <div className="space-y-6 max-w-7xl mx-auto pb-12 animate-in fade-in duration-150">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h2 className="text-xl font-bold text-[#1B1B2F] dark:text-[#ECECF5]">
            Lembretes Automáticos de Atendimento
          </h2>
          <p className="text-xs text-[#6B6B80] dark:text-[#9E9EB5]">
            Reduza faltas em até 80% enviando confirmações automáticas por WhatsApp e SMS.
          </p>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Left Col: Rules List */}
        <div className="space-y-3">
          <h3 className="text-xs font-bold uppercase tracking-wider text-[#6B6B80] dark:text-[#9E9EB5]">
            Regras de Envio
          </h3>

          <div className="space-y-2.5">
            {reminders.map((rule) => {
              const isSelected = rule.id === selectedRule?.id;
              return (
                <Card
                  key={rule.id}
                  onClick={() => {
                    setSelectedRuleId(rule.id);
                    setTemplateText(rule.template);
                    setChannel(rule.channel);
                  }}
                  className={`p-4 cursor-pointer transition-all ${
                    isSelected
                      ? 'border-[#5B4BDB] ring-2 ring-[#5B4BDB]/20 bg-[#5B4BDB]/5 dark:bg-[#5B4BDB]/10'
                      : 'hover:border-[#5B4BDB]/40'
                  }`}
                >
                  <div className="flex items-start justify-between gap-2">
                    <div className="flex items-center gap-2">
                      {rule.channel === 'whatsapp' ? (
                        <MessageSquare className="w-4 h-4 text-[#14B8A6]" />
                      ) : rule.channel === 'sms' ? (
                        <Smartphone className="w-4 h-4 text-[#5B4BDB]" />
                      ) : (
                        <Mail className="w-4 h-4 text-[#F59E0B]" />
                      )}
                      <h4 className="text-sm font-bold text-[#1B1B2F] dark:text-[#ECECF5]">
                        {rule.name}
                      </h4>
                    </div>

                    {/* Switch */}
                    <button
                      onClick={(e) => {
                        e.stopPropagation();
                        toggleReminder(rule.id);
                      }}
                      className={`relative inline-flex h-5 w-9 shrink-0 cursor-pointer rounded-full border-2 border-transparent transition-colors duration-200 ease-in-out focus:outline-none ${
                        rule.active ? 'bg-[#14B8A6]' : 'bg-[#E4E4EE] dark:bg-[#2E2E48]'
                      }`}
                      role="switch"
                      aria-checked={rule.active}
                    >
                      <span
                        className={`pointer-events-none inline-block h-4 w-4 transform rounded-full bg-white shadow-lg ring-0 transition duration-200 ease-in-out ${
                          rule.active ? 'translate-x-4' : 'translate-x-0'
                        }`}
                      />
                    </button>
                  </div>

                  <p className="text-xs text-[#6B6B80] dark:text-[#9E9EB5] mt-1">
                    Gatilho: {rule.timing}
                  </p>
                </Card>
              );
            })}
          </div>
        </div>

        {/* Center / Right: Template Editor & WhatsApp Bubble Preview */}
        <div className="lg:col-span-2 space-y-5">
          <Card className="p-5 space-y-4">
            <div className="flex items-center justify-between pb-3 border-b border-[#E4E4EE] dark:border-[#2E2E48]">
              <div>
                <h3 className="text-base font-bold text-[#1B1B2F] dark:text-[#ECECF5]">
                  Editor do Lembrete: {selectedRule?.name}
                </h3>
                <p className="text-xs text-[#6B6B80] dark:text-[#9E9EB5]">
                  Personalize as mensagens e use variáveis dinâmicas.
                </p>
              </div>

              <Badge variant={selectedRule?.active ? 'success' : 'neutral'}>
                {selectedRule?.active ? 'Ativo' : 'Pausado'}
              </Badge>
            </div>

            {/* Variable Chips */}
            <div className="space-y-1.5">
              <label className="text-xs font-semibold text-[#1B1B2F] dark:text-[#ECECF5]">
                Variáveis disponíveis (clique para inserir):
              </label>
              <div className="flex flex-wrap gap-1.5">
                {validVariables.map((v) => (
                  <button
                    key={v}
                    type="button"
                    onClick={() => insertVariable(v)}
                    className="text-xs font-mono font-medium px-2.5 py-1 rounded-lg bg-[#5B4BDB]/10 text-[#5B4BDB] hover:bg-[#5B4BDB]/20 transition-colors cursor-pointer"
                  >
                    + {v}
                  </button>
                ))}
              </div>
            </div>

            {/* Template input */}
            <div className="space-y-1.5">
              <label className="text-xs font-semibold text-[#1B1B2F] dark:text-[#ECECF5]">
                Texto da Mensagem
              </label>
              <textarea
                rows={4}
                value={templateText}
                onChange={(e) => setTemplateText(e.target.value)}
                className="w-full bg-[#F7F7FB] dark:bg-[#121224] border border-[#E4E4EE] dark:border-[#2E2E48] rounded-xl p-3 text-xs sm:text-sm text-[#1B1B2F] dark:text-[#ECECF5] focus:outline-none focus:ring-2 focus:ring-[#5B4BDB]"
              />
              <div className="flex items-center justify-between text-[11px] text-[#6B6B80]">
                <span>Contador SMS: {templateText.length} / 160 caracteres</span>
                <span>Atalho: Responda 1 para confirmar ou 2 para reagendar</span>
              </div>
            </div>

            {/* Invalid variable warning (exact spec requirement) */}
            {invalidVars.length > 0 && (
              <div className="p-3 bg-[#F59E0B]/10 border border-[#F59E0B]/30 rounded-xl flex items-start gap-2 text-xs text-[#B45309] dark:text-[#FBBF24]">
                <AlertTriangle className="w-4 h-4 shrink-0 mt-0.5" />
                <span>
                  Este modelo usa uma variável que não existe: <strong>{invalidVars[0]}</strong>. Corrija antes de ativar.
                </span>
              </div>
            )}

            {/* WhatsApp Bubble Preview */}
            <div className="pt-2">
              <label className="text-xs font-semibold text-[#1B1B2F] dark:text-[#ECECF5] block mb-2">
                Pré-visualização como bolha do WhatsApp:
              </label>
              <div className="p-4 bg-[#E5DDD5] dark:bg-[#0B141A] rounded-2xl border border-[#E4E4EE] dark:border-[#2E2E48]">
                <div className="max-w-md bg-white dark:bg-[#202C33] text-[#111B21] dark:text-[#E9EDEF] p-3 rounded-2xl rounded-tl-xs shadow-xs text-xs sm:text-sm leading-relaxed space-y-2">
                  <p className="whitespace-pre-wrap">{previewText}</p>
                  <div className="flex items-center justify-end text-[10px] text-[#667781] dark:text-[#8696A0]">
                    <span>09:00</span>
                  </div>
                </div>
              </div>
            </div>

            <div className="flex justify-end pt-2">
              <Button variant="primary" size="md" onClick={handleSave}>
                Salvar modelo
              </Button>
            </div>
          </Card>
        </div>
      </div>
    </div>
  );
}
